connections:
# 不启动ssh的配置方法  
- servicename: localhost
  host: 127.0.0.1
  port: "6379"
  password: ""
  usessh: false
  sshconfig:
    sshhost: ""
    sshport: ""
    sshusername: ""
    sshpassword: ""
# 启动ssh的配置方法     
- servicename: ceshi
  host: 127.0.0.1
  port: "6379"
  password: redispass
  usessh: true
  sshconfig:
    sshhost: 127.0.0.1
    sshport: "2203"
    sshusername: root
    sshpassword: "123456"
hostname: 127.0.0.1
port: "8088"
#启用用户登录验证 不需要此功能则将 accounts 数据块注释掉即可
accounts:
- account: "admin"
  password: "123456"
